### ISSUE TITLE
Rive animations do not respect TickerMode

### ISSUE THREAD

**Issue by goderbauer** [rive-app/rive-flutter#187]
### Description
TickerMode [1] is used in flutter to turn off animations for a subtree. However, it appears that rive is not respecting the setting.

[1] https://master-api.flutter.dev/flutter/widgets/TickerMode-class.html

### Steps To Reproduce
1. Wrap the [simple animation of the example app](https://github.com/rive-app/rive-flutter/blob/b264c5166e6ed2d9fedc63a282a8aa8591134804/example/lib/simple_animation.dart#L14) with a `TickerMode(enabled: false, child: ...)`:
```dart
      TickerMode( // new
        enabled: false, // new
        child: const Center(
          child: RiveAnimation.network(
            'https://cdn.rive.app/animations/vehicles.riv',
            fit: BoxFit.cover,
          ),
        ),
      ), // new
```

2. Launch the app, navigate to that example
3. observe that the animation is still running

### Expected behavior
The animation shouldn't be running when TickerMode is off

/cc @dnfield

**Comment by HayesGordon** [comment]
Hi @goderbauer, this should now be resolved in v0.11.14

Thanks for reporting the issue. Please reopen if you encounter an issues.

**Comment by jaggernod** [comment]
Hey @HayesGordon,
it seems like the issue is not fixed.

The ticker is [stopped](https://github.com/rive-app/rive-flutter/blob/3208fae4bf326ef14d97060bd91e60121006851d/lib/src/rive_render_box.dart#L79)  when ticket mode is disabled on the creation of the [render object](https://github.com/rive-app/rive-flutter/blob/3208fae4bf326ef14d97060bd91e60121006851d/lib/src/rive.dart#L138).
However, afterward, the render object is [attached](https://github.com/rive-app/rive-flutter/blob/3208fae4bf326ef14d97060bd91e60121006851d/lib/src/rive_render_box.dart#L206) without looking at the `tickerModeEnabled`.

That leads to just starting the ticker.
