### ISSUE TITLE
App crashes after a few seconds of running rive animation after upgrading to flutter 3.7.0 (and 3.7.1)

### ISSUE THREAD

**Issue by andrewpmoore** [rive-app/rive-flutter#288]
### Description
When running a basic app with some rive animations, flutter crashes and closes the app.
Not sure if it's related to: https://github.com/dart-lang/sdk/issues/51147

### Steps To Reproduce
https://github.com/andrewpmoore/rive_render_test

Very simple example app, just run the app
#### Source `.riv`/`.rev` file
As above

### Expected behavior
App should not crash out

### Device & Versions (please complete the following information)
- Device: Pixel 6 Pro, iphone 11, Redmi note 10 
- OS: Android SDK API Level 33
- Flutter Version: Copy-paste the output of `flutter --version`
e.g.:
```
Flutter 3.7.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7048ed95a5 (20 hours ago) • 2023-02-01 09:07:31 -0800
Engine • revision 800594f1f4
Tools • Dart 2.19.1 • DevTools 2.20.1
```

#### Additional context
Worked fine on older versions of flutter

**Comment by HayesGordon** [comment]
Similar to https://github.com/rive-app/rive-flutter/issues/253 and https://github.com/rive-app/rive-flutter/issues/281

@andrewpmoore can you confirm that it's not crashing on a profile/release build?

**Comment by andrewpmoore** [comment]
@HayesGordon yeah just tried a profile build and it doesn't crash

**Comment by HayesGordon** [comment]
@andrewpmoore should be the same issue then with compilation. Seems like they pushed a cherry pick and it should be out in a bit 🤞

**Comment by MarlonJD** [comment]
> Similar to #253 and #281
> 
> @andrewpmoore can you confirm that it's not crashing on a profile/release build?

I also tried 3.7.0 and 3.7.1. Only debug versions was crashing.

**Comment by HayesGordon** [comment]
This should be resolved in Flutter v3.7.2 🥳 

Closing this for now, please re-open if anyone encounters trouble again.

**Comment by ilawicki** [comment]
This is still reproducible on macOS and iOS with flutter 3.7.3. Debug crashes, profile works. Haven't checked Android.

**Comment by HayesGordon** [comment]
Hi @ilawicki sorry to hear this. I just tested it with the known .riv files that resulted in a crash. And I just tested and 3.7.3 appears to have solved it for me.

Do you mind sharing you .riv and I'll try to replicate. Or if you can make a reproducible example and share that will be fantastic

**Comment by ilawicki** [comment]
So I have created minimalistic app to reproduce this issue and I couldn't reproduce it. So I went back to my main project and also couldn't reproduce it now. Nothing really changed, but now it works. Strange but this is how it is. Probably something wrong on my part along the way. I guess it can be closed now again.

**Comment by HayesGordon** [comment]
Thanks for taking the time to look into this @ilawicki. I'll close this then.
