### ISSUE TITLE
Rive file with text crash

### ISSUE THREAD

**Issue by 1ns4n33** [rive-app/rive-flutter#337]
Hi, i'm using the last version of rive (0.11.8) and last of Flutter/dart.

i tried to to create a project in flutter from scratch and an empty Rive file with only a 'Test' text to verify that is not a problem related to my project, and in both projects it gives me this error when running on chrome:

Error: LateInitializationError: Field '_makeFont' has not been initialized.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49  throw_
packages/rive_common/src/rive_text_wasm.dart 13:20                            get _makeFont
packages/rive_common/src/rive_text_wasm.dart 640:23                           decodeFont
packages/rive_common/rive_text.dart 456:12                                    decode
packages/rive/src/rive_core/assets/font_asset.dart 50:17                      parseBytes
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/rive/src/rive_core/assets/font_asset.dart 49:34                      parseBytes
packages/rive/src/rive_core/assets/font_asset.dart 46:18                      decode
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/rive/src/rive_core/assets/font_asset.dart 45:22                      decode
packages/rive/src/core/importers/file_asset_importer.dart 28:17               resolveContents
packages/rive/src/rive_core/assets/file_asset_contents.dart 29:13             import
packages/rive/src/rive_file.dart 222:17                                       __
packages/rive/src/rive_file.dart 288:21                                       import
packages/rive/src/rive_file.dart 321:21                                       asset
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1661:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 784:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 813:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 584:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 657:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15           <fn>

i also tried to consult the guide but i didn't find anything about it,
am i doing something wrong? or is it a bug?

**Comment by HayesGordon** [comment]
Hi @1ns4n33 , has this issue been resolved for you?

**Comment by 1ns4n33** [comment]
Yes, with the latest version, thank you!

**Comment by HayesGordon** [comment]
Fixed in v0.11.13

Release notes:
```
Initializes Rive's text engine only when necessary when calling any of RiveFile.asset, RiveFile.network, or RiveFile.file.
You'll need to manually call RiveFile.initializeText when calling RiveFile.import directly to use text features. You can optionally only call this if you know the file needs the text engine, or you can determine if it needs it by calling RiveFile.needsTextRuntime.
```

**Comment by Saubhagya-dubey** [comment]
This Issue Still Exists for web : 

I have Three similar rive assets in a column and text only renders randomly for any one of them .

Any help would be highly appreciated.
