### ISSUE TITLE
Text - wrong font is loaded

### ISSUE THREAD

**Issue by edhom** [rive-app/rive-flutter#338]
### Description
We're trying to get the new text feature running in our projects but experiencing a problem with fonts.
The only font our test Rive uses is `Open Sans`, but somehow the asset loader wants to load `Inter-Regular` instead. 

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/fonts/Inter-Regular.ttf".
The asset does not exist or has empty data.
#0      PlatformAssetBundle.load.<anonymous closure>
asset_bundle.dart:328
<asynchronous suspension>
```

### Steps To Reproduce

<summary>
Minimal reproducible dart code:
</summary>
<details>

```dart

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  Future<Artboard> loadRiveFile() async {
    final bytes = await rootBundle.load('rive_with_text.riv');
    final file = RiveFile.import(
      bytes,
      assetLoader: LocalAssetLoader(
        fontPath: '',
        imagePath: '',
      ),
    );
    final artboard = file.mainArtboard;
    final controller =
        StateMachineController.fromArtboard(artboard, 'State Machine');
    artboard.addController(controller!);
    return artboard;
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Testing text',
      home: Scaffold(
        body: Container(
          color: Colors.black87,
          child: Center(
            child: FutureBuilder(
              future: loadRiveFile(),
              builder: (context, snapshot) {
                if (snapshot.hasData && snapshot.data != null) {
                  return Rive(
                    artboard: snapshot.data!,
                    fit: BoxFit.contain,
                  );
                } else {
                  return const SizedBox();
                }
              },
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

#### Source `.riv`/`.rev` file
https://editor.rive.app/file/showcase/503653

### Expected behavior
The text is shown
<img width="601" alt="Screenshot 2023-08-01 at 12 23 20" src="https://github.com/rive-app/rive-flutter/assets/47747733/28e88c85-e877-4a11-8ca6-75fbe3f729b9">

#### Screenshots
Text is missing...
<img width=340 src=https://github.com/rive-app/rive-flutter/assets/47747733/19c793c1-5ca8-401a-926e-d966a0546945>

### Device & Versions
- Rive: 0.11.8
- Device: iOS Simulator
- OS:  iOS 16.4
- Flutter Version:
```
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (7 weeks ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1
```

**Comment by HayesGordon** [comment]
Hi @edhom thanks for reporting. We'll push a fix for this soon

**Comment by HayesGordon** [comment]
This is fixed in v0.11.9 🙌 

Closing this but if anyone encounters issues please reopen

**Comment by tomkuschka** [comment]
@HayesGordon I just tried out @edhom code on v0.11.12 with the same rive on web and I'm still unable to see the text, unfortunately… Seems to be still an issue with font loading according to the debug console output:

```
Error while trying to load an asset: Flutter Web engine failed to fetch "assets/assets/fonts/Inter-Regular.ttf". HTTP request succeeded, but the server responded with HTTP status 404.
Error: LateInitializationError: Field '_makeFont' has not been initialized.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49  throw_
packages/rive_common/src/rive_text_wasm.dart 13:20                            get _makeFont
packages/rive_common/src/rive_text_wasm.dart 640:23                           decodeFont
packages/rive_common/rive_text.dart 456:12                                    decode
packages/rive/src/rive_core/assets/font_asset.dart 50:17                      parseBytes
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/rive/src/rive_core/assets/font_asset.dart 49:34                      parseBytes
packages/rive/src/rive_core/assets/font_asset.dart 46:18                      decode
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/rive/src/rive_core/assets/font_asset.dart 45:22                      decode
packages/rive/src/core/importers/file_asset_importer.dart 29:17               resolveContents
packages/rive/src/rive_core/assets/file_asset_contents.dart 29:13             import
packages/rive/src/rive_file.dart 222:17                                       __
packages/rive/src/rive_file.dart 288:21                                       import
packages/rive_text/main.dart 75:27                                            loadRiveFile
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1661:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 784:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 813:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 584:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 657:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15           <fn>
Error while trying to load an asset: Flutter Web engine failed to fetch "assets/assets/fonts/Inter-Regular.ttf". HTTP request succeeded, but the server responded with HTTP status 404.
Error while trying to load an asset: Flutter Web engine failed to fetch "assets/assets/fonts/Inter-Regular.ttf". HTTP request succeeded, but the server responded with HTTP status 404.
```

**Comment by SirBarksALot** [comment]
@HayesGordon still present
Flutter version: `3.13.1`
Rive package version: `0.11.14`
Rive widget tries to download font that isn't used in any place by me
Error:
`dom.dart:1423     GET http://localhost:54302/assets/assets/fonts/Inter-Regular.ttf 404 (Not Found)`
In Rive editor I use 
<img width="234" alt="image" src="https://github.com/rive-app/rive-flutter/assets/44412197/0d6c983a-b326-440a-b5fb-9096689dcb53">
Widget definition:
```dart
RiveAnimation.asset(
    'assets/animations/button.riv',
    onInit: onButtonInit,
),
```
onInit function definition:
```dart
void onButtonInit(Artboard art) {
    final TextValueRun? textRun = art.textRun('button_text');
    textRun?.text = 'Welcome!';

    buttonCtrl = StateMachineController.fromArtboard(
      art,
      'State Machine 1',
    );
    buttonCtrl?.isActive = true;
    art.addController(buttonCtrl!);
  }
```
