### ISSUE TITLE
Jank on complex rive

### ISSUE THREAD

**Issue by ductranit** [rive-app/rive-flutter#343]
### Description
My rive animation has many jank issues, the frame rate is always above 27ms
And I can see slow frame in this video

https://github.com/rive-app/rive-flutter/assets/2063905/23a6c792-ba96-436d-8195-9f3ed805ac82

It happens on both latest `master` and `stable` channels
### Steps To Reproduce
1. Go to [sample project](https://github.com/ductranit/test_rive) 
2. Run project on real device (android or ios) 
3. Click on play button
4. See slow frame error 

#### Source `.riv`/`.rev` file
https://github.com/ductranit/test_rive/blob/main/assets/factory.riv

### Expected behavior
There is no jank

#### Screenshots
![Screenshot 2023-08-30 at 14 52 16](https://github.com/rive-app/rive-flutter/assets/2063905/6e769c0f-6766-474b-84e7-691a47f3170e)

### Device & Versions (please complete the following information)
- Device: ipad air 5, Samsung galaxy s9
- OS: iPadOS 16.6, android 11
- Flutter Version: 
```
Flutter 3.13.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e1e47221e8 (7 days ago) • 2023-08-22 21:43:18 -0700
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.2 22D49 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.64.0)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources




```

**Comment by HayesGordon** [comment]
Hi @ductranit I did a quick test and it seems to be related to [this issue](https://github.com/flutter/flutter/issues/134432) with Impeller.

You can try to disable Impeller by running: `flutter run --no-enable-impeller` and seeing if you're still experiencing it.

**Comment by HayesGordon** [comment]
Closing this as it should be resolved in the latest version of Flutter. We're also working on bringing the Rive Renderer to Flutter which will provide an even faster way to render Rive content. Please reopen however, if you're still running into issues with Impeller.

**Comment by swa06** [comment]
@ductranit, did the issue get resolved?

@HayesGordon I am using Flutter 3.38.7 and still facing the same sort of jank.
