### ISSUE TITLE
lld-link : error  - flutter windows desktop

### ISSUE THREAD

**Issue by nowfalsalahudeen** [rive-app/rive-flutter#386]
lld-link : error : undefined symbol: public: bool __cdecl OT::cff2::accelerator_t::get_extents(struct hb_font_t *, unsigned int, struct hb_glyph_extents_t *) const [C:\Users\nowfa\VaasITS\edr-pos-userapp-flutter\build\windows\x64\plugins\rive_common\rive_common_plugin.vcxproj]

why this error happening? using flutter latest version

OS: windows 11
its working in macbook m2 pro windoows 11 parallel desktop, but cannot run build with windows desktop, 

clang --version
clang version 16.0.1
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin

visual studio 2022 professionnal latest version

i did not add any rive plugin to pubspec directly. i dont know which dependencies using this.

tried lots of solution that is available in google, nothing working

please help.

i have to develope the windows plugin for my current flutter project ,so need to run it on windows desktop

**Comment by philter** [comment]
Hi @nowfalsalahudeen please upgrade to 0.13.4 as the issue you are seeing has been resolved.

**Comment by nowfalsalahudeen** [comment]
@philter  but i didn't use rive in my project directly. thats why iam totally confused. 

i just add it as override dependency, its still happening

**Comment by philter** [comment]
It would be ideal if the package that uses rive_common updates to the latest but one thing you could try in the meantime is adding rive_common 0.4.8 to your dependency overrides.

**Comment by HayesGordon** [comment]
@nowfalsalahudeen you can make use of `flutter pub deps` to view a dependency graph to see where Rive is included.

Closing this issue as it is resolved in 0.13.4

But please reopen if anyone is still encountering difficulties.
